# Generated by Django 4.0.1 on 2022-01-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Site', models.CharField(max_length=100)),
                ('Instagram', models.CharField(max_length=50)),
                ('Responsavel', models.CharField(max_length=50)),
                ('Telefone_do_Responsavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_Anuncio', models.CharField(max_length=50)),
                ('Data_Inicial', models.DateField()),
                ('Data_Final', models.DateField()),
                ('Valor_do_Anuncio', models.FloatField(max_length=50)),
                ('Anexos', models.FileField(upload_to='C:/Users/lucas.silva/Documents/APP_MARKETING/imagens')),
                ('Tempo_do_Anuncio', models.PositiveIntegerField()),
                ('Cod_da_Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.empresa')),
            ],
        ),
    ]
