# Generated by Django 4.0.1 on 2022-01-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='Cod_da_Empresa',
            new_name='Codigo_da_Empresa',
        ),
    ]
