# Generated by Django 4.0.1 on 2022-01-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_rename_cod_da_empresa_anuncio_codigo_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Instagram',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Site',
            field=models.URLField(max_length=100),
        ),
    ]
